name: Push Frontend Image to Registry
run-name: Pushing frontend image to registry
on:
  push:
    branches:
      - dev
    paths:
      - frontend/**

jobs:
  stage-frontend:
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_KEY }}

      - name: Building Container Image
        run: docker build -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/Notetris:frontend-latest .

      - name: Login to DigitalOcean container registry with short-live credentials
        run: |
          credentials=$(( doctl registry login --expiry-seconds 1200 ))
          echo "::add-mask::$credentials"

      - name: Push image to DigitalOcean container registry
        run: docker push registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/Notetris:frontend-latest
