name: Test Backend
run-name: Testing Backend

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install  dependencies
        run: bun install

      - name: Run Tests
        run: bun test

